
export const data = [
    { name: "Enom", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Anom", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Ben", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Richard", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Simon", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Vinicious", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Megha",LastName:"Emma",age: 19, gender: "Female" },
    { name: "Subham",LastName:"Emma", age: 25, gender: "Male"},
    { name: "Enom", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Anom", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Ben", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Richard", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Simon", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Vinicious", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Megha",LastName:"Emma",age: 19, gender: "Female" },
    { name: "Subham",LastName:"Emma", age: 25, gender: "Male"},
    { name: "Enom", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Anom", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Ben", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Richard", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Simon", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Vinicious", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Megha",LastName:"Emma",age: 19, gender: "Female" },
    { name: "Subham",LastName:"Emma", age: 25, gender: "Male"},
    ]