
export const data = [
 
    { name: "Enom", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Anom", LastName:"Amos", age: 29, gender: "Male" },
    { name: "Ben", LastName:"Emma", age: 39, gender: "Female" },
    { name: "Richard", LastName:"Evans", age: 19, gender: "Female" },
    { name: "Simon", LastName:"Lincoln", age: 15, gender: "Male" },
    { name: "Vinicious", LastName:"Kudus", age: 19, gender: "Male" },
    { name: "Megha",LastName:"Gordon",age: 19, gender: "Female" },
    { name: "Subham",LastName:"Wahab", age: 25, gender: "female"},
    { name: "Enom", LastName:"Tindana", age: 27, gender: "Male" },
    { name: "Anom", LastName:"Kesse", age: 20, gender: "female" },
    { name: "Ben", LastName:"Okyere", age: 18, gender: "Male" },
    { name: "Richard", LastName:"Jonathan", age: 19, gender: "Male" },
    { name: "Simon", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Vinicious", LastName:"Boateng", age: 19, gender: "Male" },
    { name: "Megha",LastName:"James",age: 39, gender: "Female" },
    { name: "Subham",LastName:"Emma", age: 25, gender: "Male"},
    { name: "Enom", LastName:"Emma", age: 13, gender: "Male" },
    { name: "Anom", LastName:"Emma", age: 16, gender: "FeMale" },
    { name: "Ben", LastName:"Emma", age: 19, gender: "FeMale" },
    { name: "Megha",LastName:"Gordon",age: 19, gender: "Female" },
    { name: "Subham",LastName:"Wahab", age: 25, gender: "female"},
    { name: "Enom", LastName:"Tindana", age: 27, gender: "Male" },
    { name: "Anom", LastName:"Kesse", age: 20, gender: "female" },
    { name: "Ben", LastName:"Okyere", age: 18, gender: "Male" },
    { name: "Richard", LastName:"Jonathan", age: 19, gender: "Male" },
    { name: "Simon", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Vinicious", LastName:"Boateng", age: 19, gender: "Male" },
    { name: "Megha",LastName:"James",age: 39, gender: "Female" },
    { name: "Richard", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Simon", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Vinicious", LastName:"Emma", age: 19, gender: "FeMale" },
    { name: "Megha",LastName:"Emma",age: 19, gender: "Female" },
    { name: "Subham",LastName:"Emma", age: 25, gender: "Male"},
    { name: "Vinicious", LastName:"Boateng", age: 19, gender: "Male" },
    { name: "Megha",LastName:"James",age: 39, gender: "Female" },
    { name: "Richard", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Simon", LastName:"Emma", age: 19, gender: "Male" },
    { name: "Vinicious", LastName:"Emma", age: 19, gender: "FeMale" },
    { name: "Megha",LastName:"Emma",age: 19, gender: "Female" },
    { name: "Subham",LastName:"Emma", age: 25, gender: "Male"},
    ]